namespace TweetBook.Contracts.V1.Responses.Pagination
{
    public class Response<T>
    {
        public T Data { get; set; }

        // Only for Refit autogenerated SDK
        public Response() {}
        public Response(T response)
        {
            Data = response;
        }
    }
}
